### PR TITLE
Add PFM_test_ver_25 to automation

### PR DESCRIPTION
**Pull request by everythingfunctional**
While the input file and script were there, it wasn't being executed.

### CODE REVIEW

**Comment by praynaud** [comment]
@everythingfunctional good catch. I had created this test upon Karla's request and push up the file, but I guess neither of use got around to actually adding it to the test suite...

**Review by praynaud — COMMENTED** [review]
@everythingfunctional Is the '.sh' file intentionally blank?

**Comment by everythingfunctional** [comment]
> @everythingfunctional Is the '.sh' file intentionally blank?

It's not actually blank, it's just that the only thing that changed was the permissions.

**Review by praynaud — APPROVED** [review]
@everythingfunctional Approved!

**Pull request merged**
